---
# tasks file for roles/aws-facts
- name: Fetch Instance Info
  ec2_instance_facts:
   availability-zone: us-east-1
   tag: three-tier-app-abokhari*
  register: result

  #- name: Add host
  #add_host:
  # name: "{{ item.public_v4 }}"
  # group:
  #   - "{{ item.metadata.group }}"
  #   - "{{ item.metadata.deployment_name }}"
  # # ansible_ssh_private_key_file: ~/.ssh/openstack.pem
  # # ansible_ssh_user: cloud-user
  #with_items: "{{result.ansible_facts.openstack_servers}}"

  - name: print
    debug:
      var: result
