---
# tasks file for roles/aws-facts
- name: Fetch Instance Info
  ec2_instance_facts:
    filters:
      availability-zone: us-east-1
      "tag:instance_filter": "three-tier-app-abokhari*"
  register: result

- name: print
  debug:
    var: result
