---
# tasks file for roles/aws-facts
- name: Fetch Instance Info
  ec2_instance_facts:
   availability-zone: us-east-1
   tag: three-tier-app-abokhari*
  register: result

- name: print
  debug:
    var: result
