---
# tasks file for roles/aws-facts
- name: Gather AWS instance details
  ec2_instance_facts:
    region: us-east-1
    filters:
      "tag:instance_filter": "three-tier-app-abokhari*"
  register: result

- name: print
  debug:
    var: result

- name: Add host to in-memory intventory
  add_host:
   name: "{{ item.public_ip_address }}"
   group:
     - "{{ item.tags.AnsibleGroup }}"
   ansible_host: "{{ item.public_ip_address }}"
   ansible_ssh_private_key_file: /tmp/awskey.pem
  with_items: "{{result.instances}}"

