---
# tasks file for roles/win_service_config
- name: Install packages on windows server
  win_chocolatey:
    name: "{{ item }}"
    state: present
    params: "{{ parameters }}"
  with_items: "{{ package_name }}"

- name: Enable service
  win_service:
    name: "{{ service_name }}"
    state: started

- name: Firewall rules
  win_firewall_rule:
    action: allow
    direction: in
    enabled: true
    localport: "{{ local_port }}"
    name: "{{ service_name }}"
    protocol: "{{ protocol_name }}"
    state: present

