---
- name: Playbook to deploy infrastructure VMs in AWS
  hosts: localhost
  gather_facts: no
  vars_files:
    - vars/vars.yml
  tasks:
    - name: Create "bin" directory
      file:
        path: "~/bin"
        state: directory
        mode: 0755

    - name: Get "jq" binary
      get_url:
        url: http://www.opentlc.com/download/ansible_bootcamp/scripts/jq-linux64
        dest: "~/bin/jq"
        mode: 0755

    - name: Get scripts
      copy:
        src: "files/{{ item }}"
        dest: "~/{{ item }}"
        mode: 0755
      with_items:
        - order_svc.sh
        - common.sh

    - name: Create credentials file
      template:
        src: templates/credential.rc.j2
        dest: ~/credential.rc

    - name: Create the AWS service
      shell: "source ~/credential.rc ; ~/order_svc.sh -c 'OPENTLC Automation' -i 'Three Tier Application' -t 1 -y"

