---
# tasks file for roles/haproxy
- name: "Install {{ item }} package"
  yum:
    name: "{{ item }}"
    state: latest
  with_items:
    - httpd
    - haproxy

- name: Start and enable haproxy service
  service:
    name: haproxy
    state: started
    enabled: true

- name: Configure haproxy
  template:
    src: haproxy.cfg.j2
    dest: /etc/haproxy/haproxy.cfg
  notify: restart_haproxy

