---
# tasks file for roles/osp-flavor
- name: Create custom flavor
  os_nova_flavor:
    cloud: "{{ cloud_name }}"
    disk: "{{ disk_size }}"
    is_public: "{{ is_public }}"
    ram: "{{ ram_size }}"
    vcpus: "{{ num_vcpus }}"
    name: "{{ flavor_name }}"
    state: present

