---
- name: Provision openstack networks
  hosts: jumpbox
  gather_facts: true
  vars_files:
    - vars/vars.yml
  roles:
    - osp-network
    - osp-keypair
    - osp-flavor
    - osp-securitygroup
  tasks:
    - name: Create all VMs
      include_role:
        name: osp-vm
      with_items: "{{ vm_info }}"

## Alternate Method to create dynmaic inventory
    - name: Gather facts
      include_role:
        name: osp-facts
