---
- name: Clean up OpenStack infrastructure
  hosts: jumpbox
  gather_facts: true
  vars_files:
    - vars/vars.yml
  tasks:
    - name: Delete all VMs and associated floating IPs
      include_role:
        name: del-osp-vm
      with_items: "{{ vm_info }}"

    - name: Delete all security-groups
      include_role:
        name: del-osp-securitygroup

    - name: Delete all flavors
      include_role:
        name: del-osp-flavor

    - name: Delete all key pairs
      include_role:
        name: del-osp-keypair

    - name: Delete all networks
      include_role:
        name: del-osp-network
