---
- name: Deploy infrastructure VMs on OpenStack
  hosts: all
  gather_facts: true
  vars_files:
    - vars/vars.yml
  roles:
    - osp-flavor
    - osp-keypair
    - osp-network
    - osp-securitygroup
  tasks:
    - name: Create all VMs
      include_role:
        name: osp-vm
      with_items: "{{ vm_info }}"

