---
#
# run this playbook with ansible.cfg and inventory from the cloud-labs folder
#
- name: Deploy a 3-tier app
  hosts: all
  gather_facts: true
  vars_files:
    - ../cloud-lab/vars/vars.yml
  roles:
    - name: ../cloud-lab/roles/osp-facts
  tasks:
    - name: Delete ".ssh/known_hosts" file on workstation
      file:
        path: ~/.ssh/known_hosts
        state: absent

- name: Enable repos
  hosts: frontends, apps, appsdb
  gather_facts: False
  vars_files:
    - vars/vars.yml
  tasks:
    - name: Enable repos
      copy:
        src: "files/{{ repo_file }}"
        dest: "/etc/yum.repos.d/{{ repo_file }}"
        mode: 0644

- name: setup frontends
  hosts: frontends
  gather_facts: False
  become: yes
  roles:
    - name: haproxy

- name: setup tomcat
  hosts: apps
  gather_facts: False
  become: yes
  roles:
    - name: tomcat

- name: setup postgresql
  hosts: appsdb
  gather_facts: True
  become: yes
  roles:
    - name: postgres

- name: setup apche
  hosts: apps
  gather_facts: False
  become: yes
  roles:
    - name: apache

- name: Smoke test - Verify HAProxy
  hosts: localhost
  gather_facts: no
  become: no
  tasks:
    - name: Get web page content
      uri:
        url: "http://{{ item }}"
        return_content: yes
      register: webpage
      with_items: "{{ groups.frontends }}"

    - name: Fail if "Welcome to Tomcat" not in the returned content
      fail:
      when: "'Welcome to Tomcat' not in webpage.content"

