---
# tasks file for roles/win_ad_install
- name: Install AD-Domain-Services
  win_feature:
    name: AD-Domain-Services
    state: present

- name: Set up AD controller
  win_domain:
    dns_domain_name: "{{ ad_domain_name }}"
    safe_mode_password: "{{ ad_safe_mode_password }}"

- name: Reboot the AD server
  win_reboot:
    reboot_timeout: 900

- name: Print domain list
  command: nltest /dclist:"{{ ad_domain_name }}"

